main: me.amc.rankcraft.MainCore
name: RankCraft
version: 2.1.9011
api-version: 1.14
commands:
  rankcraft:
    description: Main RankCraft command
    aliases: [rc]
  rankcraft sync cloud:
    description: Copy local data to cloud
  rankcraft sync local:
    description: Copy cloud data to local files
